
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 1qaz3edc
    url: jdbc:mysql://172.96.193.200/demo
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: sprotsman
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
server:
  port: 80